api_key: "sk-k7ZAoJmlclL75pjwHgEcFw" #chat pwc icfr용 api key
api_base: "https://genai-sharedservice-americas.pwcinternal.com/"
pwc_model:
  openai: "azure.gpt-4o"
  claude: "bedrock.anthropic.claude3-sonnet"
  claude3_5: "bedrock.anthropic.claude-3-5-sonnet"
  google: "vertex_ai.gemini-1.5-pro"
  openai_o1: "openai.o1-2024-12-17"
  openai_o1-mini: "azure.o1-mini"
  claude3_5_v2: "bedrock.anthropic.claude-3-5-sonnet-v2"
  openai_o3_mini: "openai.o3-mini-2025-01-31"
  gemini_2.0_flash: "vertex_ai.gemini-2.0-flash"
  claude3_7: "bedrock.anthropic.claude-3-7-sonnet-v1"



